//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Builder
{
    [global::System.CodeDom.Compiler.GeneratedCode("PhoneBox.Generators", "1.0.93.54273")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class EndpointExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedEndpoints(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::PhoneBox.Generators.Tests.ITelephonyHook, global::PhoneBox.Generators.Tests.TelephonyHook>(services);
            return services;
        }

        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder AddGeneratedEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, string authorizationPolicyName = null)
        {
            foreach (global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder in global::Microsoft.AspNetCore.Builder.EndpointExtensions.AddGeneratedEndpoints(endpoints))
            {
                global::Microsoft.AspNetCore.Builder.AuthorizationEndpointConventionBuilderExtensions.RequireAuthorization(builder, authorizationPolicyName);
            }
            return endpoints;
        }
        private static global::System.Collections.Generic.IEnumerable<global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder> AddGeneratedEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
        {
            yield return global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, "/TelephonyHook/OnCallConnected", (global::PhoneBox.Generators.Tests.WebHookCallConnectedRequest content, global::PhoneBox.Generators.Tests.ITelephonyHook handler, global::Microsoft.AspNetCore.Http.HttpContext context) => handler.OnCallConnected(context, content));
            yield return global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, "/TelephonyHook/OnCallDisconnected", (global::PhoneBox.Generators.Tests.WebHookCallDisconnectedRequest content, global::PhoneBox.Generators.Tests.ITelephonyHook handler, global::Microsoft.AspNetCore.Http.HttpContext context) => handler.OnCallDisconnected(context, content));
        }
    }
}