//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBox.Generators.Tests
{
    [global::System.CodeDom.Compiler.GeneratedCode("PhoneBox.Generators", "%GENERATORVERSION%")]
    internal interface ITelephonyHook
    {
        global::System.Threading.Tasks.Task OnCallConnected(global::Microsoft.AspNetCore.Http.HttpContext context, global::PhoneBox.Generators.Tests.WebHookCallConnectedRequest content);
        global::System.Threading.Tasks.Task OnCallDisconnected(global::Microsoft.AspNetCore.Http.HttpContext context, global::PhoneBox.Generators.Tests.WebHookCallDisconnectedRequest content);
    }
}