//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBox.Generators
{
    [global::System.CodeDom.Compiler.GeneratedCode("PhoneBox.Generators", "%GENERATORVERSION%")]
    [global::System.Flags]
    internal enum SignalRHubGenerationOutputs
    {
        None = 0,
        Interface = 1,
        Implementation = 2,
        Model = 4,
        All = Interface | Implementation | Model
    }
}