//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBox.Generators.Tests
{
    internal partial class TelephonyHook : global::PhoneBox.Generators.Tests.ITelephonyHook
    {
    }
}