//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBox.Generators.Tests
{
    [global::System.CodeDom.Compiler.GeneratedCode("PhoneBox.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class WebHookCallConnectedRequest
    {
        public string FromPhoneNumber { get; }
        public string ToPhoneNumber { get; }

        public WebHookCallConnectedRequest(string fromPhoneNumber, string toPhoneNumber)
        {
            FromPhoneNumber = fromPhoneNumber;
            ToPhoneNumber = toPhoneNumber;
        }
    }
}