openapi: 3.0.1
info:
  title: PhoneBox
  version: 1.0.0
servers:
  - url: https://localhost/
paths:
  /TelephonyHook/{fromPhoneNumber}/{toPhoneNumber}:
    get:
      tags:
        - WebHook
      operationId: OnCall
      parameters:
        - name: fromPhoneNumber
          in: path
          required: true
          schema:
            type: string
        - name: toPhoneNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
      security:
      - openIdConnect: [ ]
  /TelephonyHub/ReceiveCallConnected:
    post:
      tags:
        - TelephonyHub
      operationId: ReceiveCallConnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallConnectedEvent'
        required: true
      responses: 
        '204':
          description: NoContent
      security:
      - openIdConnect: [ ]
      x-websocket: true
  /TelephonyHub/ReceiveCallDisconnected:
    post:
      tags:
        - TelephonyHub
      operationId: ReceiveCallDisconnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallDisconnectedEvent'
        required: true
      responses: 
        '204':
          description: NoContent
      security:
      - openIdConnect: [ ]
      x-websocket: true
components:
  schemas:
    CallConnectedEvent:
      required:
        - PhoneNumber
      type: object
      properties:
        PhoneNumber:
          type: string
      additionalProperties: false
    CallDisconnectedEvent:
      required:
        - PhoneNumber
      type: object
      properties:
        PhoneNumber:
          type: string
      additionalProperties: false
    CallState:
      enum:
        - None
        - Connected
        - Disconnected
    CallHangUpReason:
      enum:
        - 0
        - 1
        - 2
        - 4
      type: integer
      format: int32
      x-enum-varnames:
        - None
        - CallerClosed
        - RecipientClosed
        - BothClosed
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration