openapi: 3.0.1
info:
  title: PhoneBox
  version: 1.0.0
servers:
  - url: https://localhost/
paths:
  /TelephonyHook/OnCallConnected:
    post:
      tags:
        - TelephonyHook
      operationId: OnCallConnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebHookCallConnectedRequest'
        required: true
      responses:
        '202':
          description: Accepted
      security:
      - openIdConnect: [ ]
  /TelephonyHook/OnCallDisconnected:
    post:
      tags:
        - TelephonyHook
      operationId: OnCallDisconnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebHookCallDisconnectedRequest'
        required: true
      responses:
        '202':
          description: Accepted
      security:
      - openIdConnect: [ ]
  /TelephonyHub/ReceiveCallConnected:
    post:
      tags:
        - TelephonyHub
      operationId: ReceiveCallConnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallConnectedEvent'
        required: true
      responses:
        '202':
          description: Accepted
      security:
      - openIdConnect: [ ]
      x-websocket: true
  /TelephonyHub/ReceiveCallDisconnected:
    post:
      tags:
        - TelephonyHub
      operationId: ReceiveCallDisconnected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallDisconnectedEvent'
        required: true
      responses: 
        '202':
          description: Accepted
      security:
      - openIdConnect: [ ]
      x-websocket: true
components:
  schemas:
    WebHookCallConnectedRequest:
      required:
        - fromPhoneNumber
        - toPhoneNumber
      type: object
      properties:
        fromPhoneNumber:
          type: string
        toPhoneNumber:
          type: string
      additionalProperties: false
    WebHookCallDisconnectedRequest:
      required:
        - fromPhoneNumber
        - toPhoneNumber
      type: object
      properties:
        fromPhoneNumber:
          type: string
        toPhoneNumber:
          type: string
      additionalProperties: false
    CallConnectedEvent:
      required:
        - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: string
      additionalProperties: false
    CallDisconnectedEvent:
      required:
        - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: string
      additionalProperties: false
    CallState:
      enum:
        - None
        - Connected
        - Disconnected
      type: string
    CallHangUpReason:
      enum:
        - 0
        - 1
        - 2
        - 4
      type: integer
      format: int32
      x-enum-varnames:
        - None
        - CallerClosed
        - RecipientClosed
        - BothClosed
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration