
@startuml Incoming Call Overview

[Phone Box] As Pb
[Serviceware Module] AS module
[Telephone System] AS TK

actor "Caller" AS Caller
actor "Service Desk" AS SD
[Phone Client] AS PC


Caller -[#blue]-> TK :1. offering call
TK -[#blue]-> PC     :1. offering call
PC -[#blue]-> SD     :1. offering call
SD -[#blue]-> PC     :2. accept call
PC -[#blue]-> TK     :2. accept call
TK -[#green]-> Pb    :3. connected call
Pb -[#green]-> SD    :3. connected call
SD --> module        :4. get contextual data


legend
|= |= Communication |
|<back:blue>   </back>| Call Control |
|<back:green>  </back>| Call State Change |
|<back:black>  </back>| Contextual Data |
endlegend


@enduml